# -*- coding: utf-8 -*-
"""hw3_quicksort

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MsAKFOzDc6Yau0jMM1VOu6F3Brc02Pln
"""

num = [33, 67, 8, 13, 54, 119, 3, 84, 25, 41]

def quick_sort(array, start, end):
  if(start >= end):  #重複執行直到左右指標重疊在右指標原位再回傳
    return

  pivot = array[start]  #基準點
  left = start   #左指標
  right = end   #右指標

  while(left < right):
    while(left < right and array[right] >= pivot): #右指標向左移找到比基準點小的值/或沒有
      right -= 1

    while(left < right and array[left] <= pivot): #左指標向右移找到比基準點大的值/或沒有
      left += 1

    if(left < right):  #若有左指標大於基準點與右指標小於基準點，左右指標互換
      array[left], array[right] = array[right], array[left]

  array[start], array[left] = array[left], array[start] #修改基準點到左右指標重疊處

  quick_sort(array, start, left - 1)  #每次執行後拆分成兩段重複執行，直到左右指標重疊在右指標原位，這行為拆分的左側
  quick_sort(array, left + 1, end)  #這行為拆分的右側

quick_sort(num, 0, len(num) - 1)  #啟動函式
print("結果:", num) #輸出結果